# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build and Run

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build_and_run:
    runs-on: Chess-For-All/stockfish-api

    steps:
    - name: Make files
      uses: Chess-For-All/stockfish-api/CMakeLists.txt@ref

    - name: Build
      uses: CMakeFiles/CMakeConfigureLog.yaml@ref
